spring:
  kafka:
    bootstrap-servers: "http://localhost:9092"
    producer:
      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
      valueSerializer: "org.springframework.kafka.support.serializer.JsonSerializer"

kafka:
  topic:
    name: "users"